name: Deploy Rollback

on:
  workflow_dispatch:
    inputs:
      rollback-version:
        description: "Please, enter the pre version task definition for the execute rollback"
        required: true
      environment:
        description: "Please, enter the environment"
        required: true
        type: choice
        options: 
        - pr
        - st
        - qa

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Action ECS
        uses: actions/checkout@v3
        with:
          repository: bancodebogota/bdb-dig-do-pipelines-action-ecs-IaC
          ref: 'v1.5.1'
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/bdb-dig-do-pipelines-action-ecs-IaC
      - name: Rollback ECS
        uses: ./.github/actions/bdb-dig-do-pipelines-action-ecs-IaC/rollback
        with:
          rollback-version: ${{ inputs.rollback-version }}
          service: "nodejs-fargate-mngr-template"
          task-definition-name: "nodejs-fargate-mngr-template"
          desired-task-count: 4
          cluster: "private"
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          role-assume: ${{ secrets.AWS_ROLE_DEPLOY_BACKEND }}
          aws-region: us-east-1